### ISSUE TITLE
Issues with Consistency-based Reinforcement Learning and Ensemble Method

### ISSUE THREAD

**Issue by JeongEunhye00** [GasolSun36/APOLLO#1]
Hi,
I'm very interested in your research and would like to run your code, but I've encountered a few issues.

1. While following the README, I attempted to perform Consistency-based Reinforcement Learning, but the training doesn't seem to be progressing correctly. Is there a part missing in the code?
2. I am also curious about the method you used for the ensemble.

thank you!

**Comment by GasolSun36** [comment]
> Hi, I'm very interested in your research and would like to run your code, but I've encountered a few issues.
> 
> 1. While following the README, I attempted to perform Consistency-based Reinforcement Learning, but the training doesn't seem to be progressing correctly. Is there a part missing in the code?
> 2. I am also curious about the method you used for the ensemble.
> 
> thank you!

Hi,
Thank you for your interest in our work!

1. What specific error was reported? Could you please show it to me?
2. We use "major vote" as ensemble method.

**Comment by JeongEunhye00** [comment]
```
Traceback (most recent call last):
  File "/workspace/APOLLO/baseline/code/generator/Main.py", line 778, in <module>
    train(args)
  File "/workspace/APOLLO/baseline/code/generator/Main.py", line 288, in train
    this_logits, m_list = model(True,
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/APOLLO/baseline/code/generator/Model.py", line 285, in forward
    probs = self.softmax(option_logits)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1265, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Bert_model' object has no attribute 'softmax'
```
I encountered an error, so I added ```self.softmax = nn.Softmax(dim=-1)``` to the ```__init__``` function. 
The code runs, but the training doesn't seem to be working properly. 
![image](https://github.com/user-attachments/assets/aa061600-9f71-46b4-b902-e7a14d524a05)
There are also too many "n/a" values appearing during the training iterations. I just don't know what the problem is..😥

**Comment by GasolSun36** [comment]
> ```
> Traceback (most recent call last):
>   File "/workspace/APOLLO/baseline/code/generator/Main.py", line 778, in <module>
>     train(args)
>   File "/workspace/APOLLO/baseline/code/generator/Main.py", line 288, in train
>     this_logits, m_list = model(True,
>   File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/opt/conda/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
>     output = self._run_ddp_forward(*inputs, **kwargs)
>   File "/opt/conda/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
>     return module_to_run(*inputs[0], **kwargs[0])
>   File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/workspace/APOLLO/baseline/code/generator/Model.py", line 285, in forward
>     probs = self.softmax(option_logits)
>   File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1265, in __getattr__
>     raise AttributeError("'{}' object has no attribute '{}'".format(
> AttributeError: 'Bert_model' object has no attribute 'softmax'
> ```
> 
> I encountered an error, so I added `self.softmax = nn.Softmax(dim=-1)` to the `__init__` function. The code runs, but the training doesn't seem to be working properly. ![image](https://private-user-images.githubusercontent.com/62336723/362115502-aa061600-9f71-46b4-b902-e7a14d524a05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MjMzOTksIm5iZiI6MTcyNDkyMzA5OSwicGF0aCI6Ii82MjMzNjcyMy8zNjIxMTU1MDItYWEwNjE2MDAtOWY3MS00NmI0LWI5MDItZTdhMTRkNTI0YTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA5MTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwNWZkYmFhNmNhMTNlZTk5YTQ4NWE3OTJhMTQyMzk1ZWU3MjA3ZDU2M2I5MmU4NjA4NGY2MDQzMjgyMDU0NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q7KLskecMJqln8AALLJKWVGb0td5NVohgbG5Ekjq6M0) There are also too many "n/a" values appearing during the training iterations. I just don't know what the problem is..😥

Can you send me the sh script you run? You should warm-up a generator first (train like 80, 100 iterations), then read the generator and continue training with RL.

**Comment by JeongEunhye00** [comment]
`python -u -m torch.distributed.launch --nproc_per_node=2 --master_port=6899 ./baseline/code/generator/Main.py\
--root_path "./" \
--model_save_name generator-roberta-large \
--pretrained_model roberta \
--model_size roberta-large \
--mode train \
--features_dir ./baseline/dataset/generator/ \
--examples_dir ./baseline/dataset/generator/ \
--tags 3 \
--saved_model_path "./baseline/output/generator/30000_model.pt" \
--dataset_type finqa --rl \
--epoch 50 \
--batach_size 4 \
--gradient_accumulation_steps 4 \
--report 2000 \
--report_loss 500 \
`
I used it like this.
